# Generated by Django 2.1.7 on 2019-03-03 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedGuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsvp_code', models.CharField(max_length=8)),
                ('rsvp_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='invitedguest',
            name='rsvpModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.RSVP'),
        ),
    ]
